title: ReSwing
author: ZhouHang
email: zhouhang_1030@qq.com
description: ZhouHang's Personal Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhou-zhoukang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  zhou-zhoukang

lang: en
timezone: Asia/Shanghai
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - jekyll-whiteglass.gemspec
  - screenshot.png
  - vendor

# Social media
twitter_username:
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:
comments: false

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
